### PR TITLE
Journey ENG-7092 AT&T Click Through Demo

### PR DESCRIPTION
**Pull request by GlympseChip**
Addresses issue #1 in this ticket:
Assigned technician photo and name should not be visible until the LIVE stage. Up until that it should be 'Your Technician and the default avatar'

also, found out driver_id and duration were not being set up. there will be a corresponding ticket in journey-standalone.

### CODE REVIEW

**Comment by GlympseChip** [comment]
@j5kay PTAL

**Comment by j5kay** [comment]
To be clear, driver_id and duration were strictly defined in journey-standalone, not core. We'll bring them in as they should be common EnRoute datastream properties.

**Comment by j5kay** [comment]
This needs to be reworked architecturally from an on-going maintenance/scalability standpoint. I have pending changes, but they aren't yet ready. Please do not integrate.

**Comment by j5kay** [comment]
New changes integrated and tested with updates in the delay-avatar branch. PTAL

**Comment by GlympseChip** [comment]
LGTM

**Pull request merged**
